version: '3.4'

services:
  notification-api:
    container_name: notification-api
    image: ${REGISTRY:-DDD-MicroService-}notification-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/NotificationManagement/NotificationManagement.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:49301
    ports:
      - "49301:49301"
