version: '3.4'

services:
  ddd.notification.api:
    container_name: ddd-notification-api
    image: ${REGISTRY:-ddd-}notification-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/NotificationManagement/NotificationManagement.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:48301
    ports:
      - "48301:48301"

  ddd.seq:
    container_name: ddd-seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
